# generate_buildinfo.ps1
# Reads the VERSION file at the repo root and regenerates BuildInfo.h which
# feeds the Win32 VERSIONINFO resource (FileVersion / ProductVersion) in
# LXElauncher.rc. Pure ASCII on purpose.
param(
    [string]$VersionFile = (Join-Path $PSScriptRoot '..\..\VERSION'),
    [string]$OutFile = (Join-Path $PSScriptRoot '..\..\BuildInfo.h')
)
$ErrorActionPreference = 'Stop'

$ver = (Get-Content -LiteralPath $VersionFile -Raw).Trim()
$verNoV = $ver.TrimStart('v')
$verStr = $verNoV

$parts = @($verNoV -split '\.')
$nums = @()
foreach ($p in $parts) {
    if ($p -match '^\d+$') { $nums += [int]$p } else { $nums += 0 }
}
while ($nums.Count -lt 4) { $nums += 0 }

$lines = @(
    '#ifndef LXELAUNCHER_BUILDINFO_H'
    '#define LXELAUNCHER_BUILDINFO_H'
    ''
    '// Auto-generated by .github/scripts/generate_buildinfo.ps1 from the VERSION file.'
    '// Do not edit by hand.'
    ''
    ("#define LXE_VERSION_MAJOR {0}" -f $nums[0])
    ("#define LXE_VERSION_MINOR {0}" -f $nums[1])
    ("#define LXE_VERSION_PATCH {0}" -f $nums[2])
    ("#define LXE_VERSION_BUILD {0}" -f $nums[3])
    ('#define LXE_VERSION_STR "' + $verStr + '"')
    ''
    '#endif // LXELAUNCHER_BUILDINFO_H'
    ''
)
Set-Content -LiteralPath $OutFile -Value $lines -Encoding ASCII

Write-Output ("BuildInfo.h written for version " + $verStr)