#ifndef LXELAUNCHER_BUILDINFO_H
#define LXELAUNCHER_BUILDINFO_H

// Auto-generated by .github/scripts/generate_buildinfo.ps1 from the VERSION file.
// Do not edit by hand.

#define LXE_VERSION_MAJOR 1
#define LXE_VERSION_MINOR 0
#define LXE_VERSION_PATCH 0
#define LXE_VERSION_BUILD 0
#define LXE_VERSION_STR "1.0.0"

#endif // LXELAUNCHER_BUILDINFO_H

