# pack_webapp.ps1
# Regenerates WebApp.rc (RCDATA) from the webapp/ folder so every compile embeds
# the front-end into the exe. Resource name = relative path inside webapp,
# e.g. "js/bridge.js", "vendor/fonts/MiSans-Regular.ttf".
# Also regenerates src/win/WebAppResources.h (LXE_WEBAPP_EMBEDDED switch).
# Runtime: WebViewHost serves these in-memory via WebResourceRequested.
# NOTE: keep this file pure ASCII (PowerShell 5.1 reads BOM-less .ps1 as ANSI).
$ErrorActionPreference = 'Stop'

$proj = Split-Path -Parent $PSScriptRoot
$webapp = Join-Path $proj 'webapp'
$rcPath = Join-Path $proj 'WebApp.rc'
$hPath = Join-Path $proj 'src\win\WebAppResources.h'

if (-not (Test-Path -LiteralPath $webapp)) {
    Write-Output 'pack_webapp: webapp missing, skip embed'
    exit 0
}

$files = Get-ChildItem -LiteralPath $webapp -Recurse -File |
    Where-Object { $_.FullName -notmatch '\\\.git\\' }

$relList = @()
foreach ($f in $files) {
    $relList += ($f.FullName.Substring($webapp.Length + 1).Replace('\', '/'))
}
$relList = @($relList | Sort-Object)

$rc = @()
$rc += '// WebApp.rc : auto-generated by tools\pack_webapp.ps1 before every compile'
$rc += '// Embeds the whole webapp/ folder as named RCDATA (name = relative path).'
$rc += '#include "src/win/WebAppResources.h"'
$rc += 'LANGUAGE 0, 0'
$rc += ''
foreach ($rel in $relList) {
    $line = '"' + $rel + '" RCDATA "webapp/' + $rel + '"'
    $rc += $line
}
$rc += ''
Set-Content -LiteralPath $rcPath -Value $rc -Encoding UTF8

$hdr = @(
    '#ifndef WEBAPPRESOURCES_H'
    '#define WEBAPPRESOURCES_H'
    '// auto-generated by tools\pack_webapp.ps1'
    '#define LXE_WEBAPP_EMBEDDED 1'
    '#define LXE_WEBAPP_FILE_COUNT ' + $relList.Count
    '#endif'
    ''
)
Set-Content -LiteralPath $hPath -Value $hdr -Encoding UTF8

Write-Output ('pack_webapp: embedded ' + $relList.Count + ' files -> WebApp.rc')